In [1]:
import sys
sys.path.append("/Users/Hallshit/Documents/cryptoAPI/venv/lib/python3.5/site-packages")
from binance.client import Client
import pandas as pd

In [2]:
api_key = '7tDBYdWpcmbHLSmJJKVd2aCVbzyGwdQ3hDgSfw5MrrXSpjAoufMW5Tkk02W1JiPv'
api_secret = '98BCmuZh6yFLJUYtJ7WtZtCqiMeNTuauxKfzrRQQ82RNnG01HJdxmuXzxZ5SSnyU'
client = Client(api_key, api_secret)

In [19]:
ob = client.get_order_book(symbol="BTCUSDT")
st = client.get_server_time()['serverTime']

In [20]:
asks = ob['asks']
bids = ob['bids']
bids

[['7540.01000000', '0.38607400', []],
 ['7540.00000000', '19.51833300', []],
 ['7539.50000000', '2.91624800', []],
 ['7538.86000000', '0.01107000', []],
 ['7538.38000000', '0.00132800', []],
 ['7538.28000000', '0.00000200', []],
 ['7537.78000000', '0.50000000', []],
 ['7537.62000000', '0.00132800', []],
 ['7537.50000000', '0.24367100', []],
 ['7537.27000000', '0.00238600', []],
 ['7537.17000000', '0.01072500', []],
 ['7537.00000000', '0.16840400', []],
 ['7536.17000000', '0.50000000', []],
 ['7535.68000000', '0.00400000', []],
 ['7535.10000000', '0.08642500', []],
 ['7535.00000000', '0.09026900', []],
 ['7534.70000000', '0.00132900', []],
 ['7534.29000000', '0.50000000', []],
 ['7534.00000000', '1.00000000', []],
 ['7533.76000000', '0.01335300', []],
 ['7533.03000000', '2.14000000', []],
 ['7532.68000000', '0.51848200', []],
 ['7532.40000000', '0.50501100', []],
 ['7532.15000000', '0.60885100', []],
 ['7532.03000000', '0.10000000', []],
 ['7532.00000000', '0.10184900', []],
 ['7531.88000000', '0.00132900', []],
 ['7531.23000000', '0.00132900', []],
 ['7531.10000000', '1.00000000', []],
 ['7531.00000000', '1.00000000', []],
 ['7530.92000000', '2.01000000', []],
 ['7530.60000000', '0.00132900', []],
 ['7530.29000000', '0.19532000', []],
 ['7530.12000000', '0.00200000', []],
 ['7530.00000000', '1.63423600', []],
 ['7529.63000000', '0.14497200', []],
 ['7529.32000000', '2.50000000', []],
 ['7529.14000000', '0.00259200', []],
 ['7529.00000000', '0.08808100', []],
 ['7528.83000000', '0.01074800', []],
 ['7528.51000000', '0.30921500', []],
 ['7528.13000000', '0.00720700', []],
 ['7528.00000000', '4.00000000', []],
 ['7527.98000000', '0.04380000', []],
 ['7527.34000000', '0.17183200', []],
 ['7527.20000000', '0.00191600', []],
 ['7527.00000000', '0.05637200', []],
 ['7526.90000000', '0.00265200', []],
 ['7526.37000000', '0.00396100', []],
 ['7526.22000000', '0.17183200', []],
 ['7526.04000000', '3.00000000', []],
 ['7526.03000000', '1.50418200', []],
 ['7526.00000000', '0.04630700', []],
 ['7525.87000000', '1.00000000', []],
 ['7525.52000000', '0.00596600', []],
 ['7525.00000000', '1.07719200', []],
 ['7524.65000000', '0.01075900', []],
 ['7524.56000000', '0.00265500', []],
 ['7524.49000000', '0.01470900', []],
 ['7524.43000000', '0.09435900', []],
 ['7524.00000000', '0.00134200', []],
 ['7523.95000000', '0.00137900', []],
 ['7523.79000000', '0.10000000', []],
 ['7523.57000000', '0.17183200', []],
 ['7523.21000000', '0.08044000', []],
 ['7523.17000000', '0.00332300', []],
 ['7523.00000000', '1.05134600', []],
 ['7522.91000000', '0.00278300', []],
 ['7522.22000000', '0.00133000', []],
 ['7522.16000000', '0.00397500', []],
 ['7522.00000000', '2.13205500', []],
 ['7521.90000000', '0.00133500', []],
 ['7521.75000000', '0.02654300', []],
 ['7521.74000000', '0.01463300', []],
 ['7521.66000000', '1.91999600', []],
 ['7521.58000000', '0.04100000', []],
 ['7521.57000000', '0.00723100', []],
 ['7521.45000000', '0.00398900', []],
 ['7521.40000000', '0.25000000', []],
 ['7521.27000000', '0.00145600', []],
 ['7521.16000000', '6.44640000', []],
 ['7521.15000000', '0.54999900', []],
 ['7521.06000000', '0.00962100', []],
 ['7521.00000000', '2.41059400', []],
 ['7520.99000000', '0.03330600', []],
 ['7520.98000000', '0.22273200', []],
 ['7520.72000000', '0.01470900', []],
 ['7520.30000000', '0.00266100', []],
 ['7520.26000000', '0.00151300', []],
 ['7520.00000000', '1.71955100', []],
 ['7519.88000000', '0.02589600', []],
 ['7519.86000000', '0.01327200', []],
 ['7519.79000000', '0.17183200', []],
 ['7519.40000000', '0.00230100', []],
 ['7519.39000000', '0.01994900', []],
 ['7519.13000000', '0.01470900', []],
 ['7519.05000000', '0.00398300', []],
 ['7519.00000000', '0.03280200', []],
 ['7518.94000000', '0.00190200', []],
 ['7518.10000000', '0.00422000', []]]

In [21]:
df = pd.DataFrame(columns=["server_time", "price", "volume", "bid/ask"])
df.head()

Empty DataFrame
Columns: [server_time, price, volume, bid/ask]
Index: []

In [25]:
for i in asks:
    df = df.append({"server_time": st, "price": i[0], "volume": i[1], "bid/ask": "ask"}, ignore_index=True)
    
for i in bids:
    df = df.append({"server_time": st, "price": i[0], "volume": i[1], "bid/ask": "bid"}, ignore_index=True)

In [23]:
df['server_time'] = pd.to_datetime(df['server_time'], unit='ms')
df.sort_values('price').head()

                server_time          price      volume bid/ask
199 2018-08-01 20:21:04.593  7518.10000000  0.00422000     ask
198 2018-08-01 20:21:04.593  7518.94000000  0.00190200     ask
197 2018-08-01 20:21:04.593  7519.00000000  0.03280200     ask
196 2018-08-01 20:21:04.593  7519.05000000  0.00398300     ask
195 2018-08-01 20:21:04.593  7519.13000000  0.01470900     ask

In [28]:
df.loc[df['bid/ask'] == 'ask']

                    server_time          price      volume bid/ask
0    2018-08-01 20:21:04.593000  7541.00000000  0.02435100     ask
1    2018-08-01 20:21:04.593000  7541.01000000  0.03000000     ask
2    2018-08-01 20:21:04.593000  7541.03000000  0.00401100     ask
3    2018-08-01 20:21:04.593000  7541.98000000  0.30999800     ask
4    2018-08-01 20:21:04.593000  7541.99000000  0.00283700     ask
5    2018-08-01 20:21:04.593000  7542.00000000  2.16558100     ask
6    2018-08-01 20:21:04.593000  7543.00000000  0.00267000     ask
7    2018-08-01 20:21:04.593000  7543.99000000  0.09646700     ask
8    2018-08-01 20:21:04.593000  7544.93000000  0.78750400     ask
9    2018-08-01 20:21:04.593000  7545.00000000  0.00570700     ask
10   2018-08-01 20:21:04.593000  7546.00000000  0.02847500     ask
11   2018-08-01 20:21:04.593000  7546.06000000  1.98622500     ask
12   2018-08-01 20:21:04.593000  7546.13000000  0.00198600     ask
13   2018-08-01 20:21:04.593000  7546.24000000  0.50000000     ask
14   2018-08-01 20:21:04.593000  7546.45000000  0.49498800     ask
15   2018-08-01 20:21:04.593000  7546.55000000  0.03615300     ask
16   2018-08-01 20:21:04.593000  7547.77000000  0.50000000     ask
17   2018-08-01 20:21:04.593000  7548.32000000  1.07000000     ask
18   2018-08-01 20:21:04.593000  7548.84000000  1.39664200     ask
19   2018-08-01 20:21:04.593000  7549.16000000  0.48151700     ask
20   2018-08-01 20:21:04.593000  7549.39000000  0.50000000     ask
21   2018-08-01 20:21:04.593000  7549.97000000  2.28000000     ask
22   2018-08-01 20:21:04.593000  7550.00000000  9.62155500     ask
23   2018-08-01 20:21:04.593000  7550.56000000  0.19765000     ask
24   2018-08-01 20:21:04.593000  7550.62000000  0.03973100     ask
25   2018-08-01 20:21:04.593000  7551.00000000  0.04087000     ask
26   2018-08-01 20:21:04.593000  7551.64000000  1.40000000     ask
27   2018-08-01 20:21:04.593000  7552.01000000  0.00000100     ask
28   2018-08-01 20:21:04.593000  7554.27000000  0.09780000     ask
29   2018-08-01 20:21:04.593000  7554.34000000  0.00142500     ask
..                          ...            ...         ...     ...
270               1533154864593  7578.00000000  0.02073300     ask
271               1533154864593  7579.00000000  0.07947700     ask
272               1533154864593  7580.00000000  3.95402800     ask
273               1533154864593  7580.13000000  0.00146900     ask
274               1533154864593  7580.18000000  0.01470500     ask
275               1533154864593  7580.53000000  0.00647000     ask
276               1533154864593  7580.80000000  0.00195400     ask
277               1533154864593  7580.87000000  0.00132000     ask
278               1533154864593  7580.97000000  0.00132000     ask
279               1533154864593  7581.44000000  0.01469600     ask
280               1533154864593  7582.33000000  4.66642700     ask
281               1533154864593  7582.94000000  0.02570700     ask
282               1533154864593  7583.25000000  0.01070300     ask
283               1533154864593  7583.29000000  0.00134000     ask
284               1533154864593  7583.61000000  0.17175100     ask
285               1533154864593  7583.72000000  0.01470100     ask
286               1533154864593  7583.96000000  0.17183200     ask
287               1533154864593  7584.00000000  0.10020200     ask
288               1533154864593  7584.30000000  0.00527500     ask
289               1533154864593  7584.66000000  0.00659200     ask
290               1533154864593  7584.87000000  0.01470900     ask
291               1533154864593  7584.95000000  0.24596500     ask
292               1533154864593  7585.00000000  0.84594300     ask
293               1533154864593  7585.71000000  0.01335500     ask
294               1533154864593  7586.00000000  0.03700000     ask
295               1533154864593  7586.23000000  0.02981500     ask
296               1533154864593  7586.29000000  0.34778200     ask
297               1533154864593  7586.39000000  0.00132000     ask
298               1533154864593  7587.00000000  0.03975300     ask
299               1533154864593  7587.45000000  0.01069100     ask

[300 rows x 4 columns]